### ISSUE TITLE
프로젝트 필요성 조사

### ISSUE THREAD

**Issue by BiteSnail** [BiteSnail/RRG#2]
# 개요
현재 프로젝트의 필요성에 대한 기사 혹은 논문, 통계 등 다양한 형태의 자료 찾기    
해당 이슈 아래에 적어주세요.

**Comment by BiteSnail** [comment]
[링크](https://hrcopinion.co.kr/archives/19151) 에 재활용 쓰레기 분리배출 인식에 대해서 조사 및 결과 해석이 있습니다.    
여기에서 분리 배출 지식 측정 결과를 이용해 해당 주제의 필요성을 뒷받침하고, 교육 게임을 선택한 이유에 대한 근거로 재활용 및 음식물 쓰레기 처리가 가구에서 주로 한 명이 맡기 때문에 자연스러운 생활 속 폐기물 분리배출 관련 학습이 이루어지기 힘들다는 점을 어필하면 좋을 것 같습니다.    
추가로 [링크](https://sti.kostat.go.kr/window/2018a/main/2018_sum_18.html#end) 의 내용을 보면 통계청 자료로 국민 다수가 쓰레기 분리 배출 방법을 잘 모른다고 한 한국갤럽조사연구소에서 조사한 내용이 담겨 있습니다. 이를 추가로 이용하면 좋을 것 같네요.

타겟층은 분리수거 배출방법을 배워야 하는 7~16세 이하의 청소년들이 어떨까 싶습니다.

**Comment by zizioz** [comment]
타겟층 7~16세 이하 청소년들 괜찮을 것 같습니다.

<논문>
https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE09365970
중학교 대상 쓰레기 관리 교육 -> 중학생들의 설문조사 결과, 학생 대부분이 쓰레기에 대한 교육이 필요하다고 생각하지만, 학교 내에서 진행되는 교육 내용이 다소 지루하다는 설문 결과를 사용하여 게임을 통한 학습에 대해 어필할 수 있을 것 같습니다.
<기사>
https://news.mt.co.kr/mtview.php?no=2022092518250398038
한국인 20대~60대 분리배출 상식이 부족하다는 결과로 어린이와 청소년을 대상으로 하는 교육의 중요성을 어필할 수 있을 것 같습니다. 
+) 퀴즈 문제랑 정답률로 게임 난이도 설정에 참고할 수도 있을 것 같습니다.

**Comment by GyeongminYun** [comment]
[링크](https://www.donga.com/news/It/article/all/20201231/104713889/1)
1. ‘내 손안의 분리배출’앱 or 환경부 홈페이지 및 전국 시/도 홈페이지 '재활용도우미’와 같은 기존의 분리수거 도우미 서비스가 있지만, RRG 교육용 게임을 통해 청소년들이 재활용 콘텐츠에 관심을 갖게 만들어 좀 더 쉽게 복잡한 지식을 즐겁게 배울 수 있다는 것을 어필하면 좋을 것 같습니다. 
2. 올바른 방법으로 배출하지 않는 쓰레기가 많아 분리수거 참여 비율에 비해 실질적인 재활용률은 낮다는 내용이 담겨 있습니다.
3. 저희가 개발할 때 이 링크에 분리수거 방법이 자세히 나와 있어 참고하면 좋을 것 같습니다.

**Comment by gamzachips** [comment]
투명페트병 분리배출
http://www.joongboo.com/news/articleView.html?idxno=363606858
폐의약품
https://www.hankyung.com/article/202309042297i
=> 방법을 잘 몰라서 분리배출이 잘 이루어지지 않는 폐기물의 예시입니다. 이러한 폐기물들의 분리배출 방법에 대한 구체적인 정보를 제시하여 수거율,재활용률을 높일 수 있을 것입니다. 

https://www.nocutnews.co.kr/news/5438031
http://www.bzeronews.com/news/articleView.html?idxno=608030
http://view.asiae.co.kr/news/view.htm?idxno=2017031407253961183
=> 한국에 거주하는 외국인들은 분리배출에 익숙하지 않고 잘 모르는 경우가 많습니다. 특히 분리배출 안내문이 한글로 되어있어 이해하는 데 어려움을 겪는다고 합니다. 따라서 그림(사진) 위주의 게임을 통해 직접 쓰레기를 분류해보도록하여 효율적으로 학습을 유도할 수 있을 것입니다.
